language: node_js
node_js:
- '8'
script: yarn run package
deploy:
  - provider: npm
    email: it@metricly.com
    api_key:
      secure: fS78bO+N5MWoHpwfNr0/OtDz1aMIZPBLWMVrr89X58mhjpA2g+SwQZhFLb3wIP3gBKzkBYRUxuzXf8NI/MbU1bjB4bvnCbOgeGXGboTc8YGD3Lsp6dtNsKjPjJCfC5rRlXs2fEt8pvmhbSg6q3l+BUxGHfMpjAOow44t6xOj+PKwEG0faAWgE7re5zoAoKUKfNImQ/4vtViYCuSMaR6o5syfp/0MMGgAi6es/KmYs6YLlJ/AjGneBW3iWJLhYyHWKU5AbbFMchLz1jI2wTvg3PvHJo3+TbEcaAH+B994bHpTgBZrdN2JD8pLbAILYX+gS7wGjjyXi4KS0YUS4K4pFIhf7zuUEem/g3bG9C1o13RuqQkz5uvKEKPAQjG6FsKwk+LyMuX2aMKRwBM/Ea3NgTvQIYsCoNXqqMWlliDvkJDpCivfi2pTzDd2CzuviNFZyy/DhrjKDe3aLejmt/u8sVwFrLwR8zhXMNwNbgcmRvChg5y7mtCsYejQjstFaxOYV2x9wF0AwJMu4G3MXZMTJjenIHOQ/tFJ8OrXHOaqwsxk/IPvKG2y1woduejRzFJTrhaofIDxdODN/JvKgqz2eHKUvs9W+8AuibqEMzJn0ux7FvqNkH7RxqK8Qmx2g6PB9oVNfqnyOY/wpoTrMUzdBBU2OrHhFHhePR9BZzgnngc=
    skip_cleanup: true
    on:
      tags: true
      repo: metricly/metricly-cli
  - provider: releases
    api_key:
      secure: ipuqU5VOMov44yGn0bX48tvyAsO/NbRwjU8Fibf06Be8U/IaiBhS+uvdcr1fxiVxd0ewZcW/zNDfJIZBLk2hAOL9YfSyS/uaA7TOnWbMV2SEnWtuVVySF65tfOkhqK14PF9f4T5t8dZTFuu/4HTgKwdbl2x+zmgz/QwxMbadOrO7YutjklrilMXaqj1UeATkho3vZ3iMzheN5uh1d/MFba055VKWq1Vav43OuKOpZPVsuS5hpDfAzvBWuBQAdxlIxYkRuEcFz2fIwBOmO5+AwwjE+NZd3PiKVgzaoaaF1cBcq3qGi+wrwhOKSKAnG8HPqAkydS+p+Ra55iR2VnxBSgJvkv6RuXcCWfpbDPwdkIh9qyJbSRIk40WrrOiFmV678qMmixuxi3dhaCDbxb+P8O9h4vtnJYoAbi+wTIUa3Hm9QfBY0Pw6xB/Nq+XGfilFkPBdOlK14XGRUj2sL4JtSr5NHJxEuxzCnYUzlLVUTgKvZX3N50nj0cmZ6quYTDDhpwJn0vstzXTIHDMWKPjlnghyulPLrPHTP9XWicvalOXvO+stuAXh6ppF9TYAZMPusPdk+zoISTSQtHG+8Dv3xY5GvZ19+PkWpGGQq5srl9ewi0MRnGEU6hu6Z9HThRT+YimOthtUJlGn/WNiAtApteXtRNb5NnWitFUq4eP0/EI=
    file_glob: true
    file: metricly-cli-*
    skip_cleanup: true
    on:
      tags: true
      repo: metricly/metricly-cli
