language: node_js
node_js:
- '8'
script: 
  - yarn run test
  - yarn run package
deploy:
  - provider: npm
    email: it@metricly.com
    api_key:
      secure: Nc5sVUY6b6Gd8C8PLDhgfNCv0mCOKh74OrwADNMnqHQPvPZwTICRKIN/zB9BUAv/uHrQMyjpjnWYc+Q9+NnlApk9D9Kmdc5KvdTL2lhI8UF3eP92C776CztSG/QVKCexPQcwU3nRvVvdY04ZZE9h1EeVlTTzqXzLb8ho0L6IOv1/HN2jIEAcNifxMb+Xf3tzGKBk1+cq8piCFstW2WkpDczy0ygSLRIejwpL77CGC6+7TAZnKXUdYObQc6wl9as+5Faa3eV0wkX+Osqq7ZPSIsv1BlUOxPKAOYU95GS3JXSNjB8dbHqtBtWOdAmKDaXZfNO035VVSEcNHcZLTdPwuqGn/uVOYY/Daa988NQpPq6E7HSNOcsSQLFpsXi31gTY1XaACX5O79kRLZcopGpxZtBzVFq2UVLsKqUTQrrUtZVLIjIrx5K6vz8QuKcwwNDE8NbZOOMc86nXWGNtrH+uaeC3fGKu0m11rHnx5GxGZ04085TfgoijoITGtFAIAFML/1OpfDU9CRXExg9VSjYEa2alA0HXWGc3gtTN4UoeFz1LjRu2pd3FDqmUqo506ByWxeKxFn+s5qXdLJZw6kB8d1K/5biTdnEzZFs5fi47Qh6DaePH+gh4eK+zehUX4rHR11Lc1w3zTT1f6cYMXDmr6WcOxdgpwq2WzH1Obv3qL5M=
    skip_cleanup: true
    on:
      tags: true
      repo: metricly/metricly-cli
  - provider: releases
    api_key:
      secure: ipuqU5VOMov44yGn0bX48tvyAsO/NbRwjU8Fibf06Be8U/IaiBhS+uvdcr1fxiVxd0ewZcW/zNDfJIZBLk2hAOL9YfSyS/uaA7TOnWbMV2SEnWtuVVySF65tfOkhqK14PF9f4T5t8dZTFuu/4HTgKwdbl2x+zmgz/QwxMbadOrO7YutjklrilMXaqj1UeATkho3vZ3iMzheN5uh1d/MFba055VKWq1Vav43OuKOpZPVsuS5hpDfAzvBWuBQAdxlIxYkRuEcFz2fIwBOmO5+AwwjE+NZd3PiKVgzaoaaF1cBcq3qGi+wrwhOKSKAnG8HPqAkydS+p+Ra55iR2VnxBSgJvkv6RuXcCWfpbDPwdkIh9qyJbSRIk40WrrOiFmV678qMmixuxi3dhaCDbxb+P8O9h4vtnJYoAbi+wTIUa3Hm9QfBY0Pw6xB/Nq+XGfilFkPBdOlK14XGRUj2sL4JtSr5NHJxEuxzCnYUzlLVUTgKvZX3N50nj0cmZ6quYTDDhpwJn0vstzXTIHDMWKPjlnghyulPLrPHTP9XWicvalOXvO+stuAXh6ppF9TYAZMPusPdk+zoISTSQtHG+8Dv3xY5GvZ19+PkWpGGQq5srl9ewi0MRnGEU6hu6Z9HThRT+YimOthtUJlGn/WNiAtApteXtRNb5NnWitFUq4eP0/EI=
    file_glob: true
    file: metricly-cli-*
    skip_cleanup: true
    on:
      tags: true
      repo: metricly/metricly-cli
