language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: it@metricly.com
  api_key:
    secure: fS78bO+N5MWoHpwfNr0/OtDz1aMIZPBLWMVrr89X58mhjpA2g+SwQZhFLb3wIP3gBKzkBYRUxuzXf8NI/MbU1bjB4bvnCbOgeGXGboTc8YGD3Lsp6dtNsKjPjJCfC5rRlXs2fEt8pvmhbSg6q3l+BUxGHfMpjAOow44t6xOj+PKwEG0faAWgE7re5zoAoKUKfNImQ/4vtViYCuSMaR6o5syfp/0MMGgAi6es/KmYs6YLlJ/AjGneBW3iWJLhYyHWKU5AbbFMchLz1jI2wTvg3PvHJo3+TbEcaAH+B994bHpTgBZrdN2JD8pLbAILYX+gS7wGjjyXi4KS0YUS4K4pFIhf7zuUEem/g3bG9C1o13RuqQkz5uvKEKPAQjG6FsKwk+LyMuX2aMKRwBM/Ea3NgTvQIYsCoNXqqMWlliDvkJDpCivfi2pTzDd2CzuviNFZyy/DhrjKDe3aLejmt/u8sVwFrLwR8zhXMNwNbgcmRvChg5y7mtCsYejQjstFaxOYV2x9wF0AwJMu4G3MXZMTJjenIHOQ/tFJ8OrXHOaqwsxk/IPvKG2y1woduejRzFJTrhaofIDxdODN/JvKgqz2eHKUvs9W+8AuibqEMzJn0ux7FvqNkH7RxqK8Qmx2g6PB9oVNfqnyOY/wpoTrMUzdBBU2OrHhFHhePR9BZzgnngc=
  skip_cleanup: true
  on:
    tags: true
    repo: metricly/metricly-cli
